import type { PersonalBlog, LCBlog } from "@/lib/types"

export const personalBlogs: PersonalBlog[] = [
  {
    id: "1",
    title: "Getting Started with Next.js 15",
    status: "published",
    priority: "high",
    tags: ["nextjs", "react", "tutorial"],
    author: "John Doe",
    heroImage: "/nextjs-logo.png",
    readTime: 8,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    language: "en",
  },
  {
    id: "2",
    title: "Understanding Dijkstra's Algorithm",
    status: "draft",
    priority: "medium",
    tags: ["algorithms", "graphs", "computer-science"],
    author: "John Doe",
    readTime: 12,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    language: "en",
  },
  {
    id: "3",
    title: "Building Scalable APIs with Node.js",
    status: "published",
    priority: "high",
    tags: ["nodejs", "api", "backend"],
    author: "John Doe",
    heroImage: "/nodejs-api-concept.png",
    readTime: 15,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
    language: "en",
  },
  {
    id: "4",
    title: "CSS Grid vs Flexbox: A Complete Guide",
    status: "published",
    priority: "low",
    tags: ["css", "frontend", "design"],
    author: "John Doe",
    heroImage: "/css-layout.jpg",
    readTime: 10,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-08"),
    language: "en",
  },
  {
    id: "5",
    title: "Introduction to TypeScript Generics",
    status: "draft",
    priority: "medium",
    tags: ["typescript", "programming", "tutorial"],
    author: "John Doe",
    readTime: 7,
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    language: "en",
  },
  {
    id: "6",
    title: "Mastering React Hooks",
    status: "published",
    priority: "high",
    tags: ["react", "hooks", "frontend"],
    author: "John Doe",
    heroImage: "/react-hooks.png",
    readTime: 14,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-04"),
    language: "en",
  },
  {
    id: "7",
    title: "Database Indexing Strategies",
    status: "published",
    priority: "medium",
    tags: ["database", "performance", "sql"],
    author: "John Doe",
    readTime: 11,
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2023-12-30"),
    language: "en",
  },
  {
    id: "8",
    title: "Microservices Architecture Patterns",
    status: "draft",
    priority: "high",
    tags: ["architecture", "microservices", "backend"],
    author: "John Doe",
    readTime: 18,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    language: "en",
  },
  {
    id: "9",
    title: "Web Performance Optimization Techniques",
    status: "published",
    priority: "medium",
    tags: ["performance", "web", "optimization"],
    author: "John Doe",
    heroImage: "/performance.jpg",
    readTime: 13,
    createdAt: new Date("2023-12-20"),
    updatedAt: new Date("2023-12-22"),
    language: "en",
  },
  {
    id: "10",
    title: "GraphQL vs REST: Making the Right Choice",
    status: "published",
    priority: "low",
    tags: ["api", "graphql", "rest"],
    author: "John Doe",
    readTime: 9,
    createdAt: new Date("2023-12-15"),
    updatedAt: new Date("2023-12-16"),
    language: "en",
  },
  {
    id: "11",
    title: "Docker Containerization Best Practices",
    status: "published",
    priority: "high",
    tags: ["docker", "devops", "containers"],
    author: "John Doe",
    heroImage: "/docker-containers.png",
    readTime: 16,
    createdAt: new Date("2023-12-10"),
    updatedAt: new Date("2023-12-12"),
    language: "en",
  },
  {
    id: "12",
    title: "Authentication with JWT and OAuth",
    status: "draft",
    priority: "high",
    tags: ["security", "authentication", "jwt"],
    author: "John Doe",
    readTime: 12,
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
    language: "en",
  },
  {
    id: "13",
    title: "Serverless Functions with AWS Lambda",
    status: "published",
    priority: "medium",
    tags: ["serverless", "aws", "cloud"],
    author: "John Doe",
    readTime: 10,
    createdAt: new Date("2023-12-05"),
    updatedAt: new Date("2023-12-07"),
    language: "en",
  },
  {
    id: "14",
    title: "Testing React Applications with Jest",
    status: "published",
    priority: "low",
    tags: ["testing", "react", "jest"],
    author: "John Doe",
    heroImage: "/testing-react.jpg",
    readTime: 11,
    createdAt: new Date("2023-11-28"),
    updatedAt: new Date("2023-11-30"),
    language: "en",
  },
  {
    id: "15",
    title: "State Management with Redux Toolkit",
    status: "archived",
    priority: "low",
    tags: ["redux", "state-management", "react"],
    author: "John Doe",
    readTime: 15,
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2023-11-22"),
    language: "en",
  },
  {
    id: "16",
    title: "Building Progressive Web Apps",
    status: "published",
    priority: "medium",
    tags: ["pwa", "web", "mobile"],
    author: "John Doe",
    heroImage: "/pwa-concept.png",
    readTime: 14,
    createdAt: new Date("2023-11-15"),
    updatedAt: new Date("2023-11-17"),
    language: "en",
  },
  {
    id: "17",
    title: "Kubernetes Orchestration Guide",
    status: "draft",
    priority: "high",
    tags: ["kubernetes", "devops", "orchestration"],
    author: "John Doe",
    readTime: 20,
    createdAt: new Date("2024-01-27"),
    updatedAt: new Date("2024-01-27"),
    language: "en",
  },
  {
    id: "18",
    title: "WebSocket Real-time Communication",
    status: "published",
    priority: "medium",
    tags: ["websocket", "real-time", "networking"],
    author: "John Doe",
    readTime: 12,
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-12"),
    language: "en",
  },
  {
    id: "19",
    title: "Machine Learning Basics for Developers",
    status: "published",
    priority: "low",
    tags: ["machine-learning", "ai", "python"],
    author: "John Doe",
    heroImage: "/ml-basics.jpg",
    readTime: 17,
    createdAt: new Date("2023-11-05"),
    updatedAt: new Date("2023-11-07"),
    language: "en",
  },
  {
    id: "20",
    title: "CI/CD Pipeline Setup with GitHub Actions",
    status: "published",
    priority: "high",
    tags: ["ci-cd", "github", "automation"],
    author: "John Doe",
    readTime: 13,
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-11-03"),
    language: "en",
  },
  {
    id: "21",
    title: "Responsive Design Principles",
    status: "published",
    priority: "medium",
    tags: ["design", "css", "responsive"],
    author: "John Doe",
    heroImage: "/responsive-design.png",
    readTime: 9,
    createdAt: new Date("2023-10-25"),
    updatedAt: new Date("2023-10-27"),
    language: "en",
  },
  {
    id: "22",
    title: "MongoDB Schema Design Patterns",
    status: "draft",
    priority: "medium",
    tags: ["mongodb", "database", "nosql"],
    author: "John Doe",
    readTime: 14,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
    language: "en",
  },
  {
    id: "23",
    title: "Accessibility in Modern Web Apps",
    status: "published",
    priority: "high",
    tags: ["accessibility", "a11y", "web"],
    author: "John Doe",
    readTime: 11,
    createdAt: new Date("2023-10-20"),
    updatedAt: new Date("2023-10-22"),
    language: "en",
  },
  {
    id: "24",
    title: "Caching Strategies for Web Applications",
    status: "published",
    priority: "medium",
    tags: ["caching", "performance", "backend"],
    author: "John Doe",
    heroImage: "/caching-strategies.jpg",
    readTime: 10,
    createdAt: new Date("2023-10-15"),
    updatedAt: new Date("2023-10-17"),
    language: "en",
  },
  {
    id: "25",
    title: "Error Handling Best Practices",
    status: "published",
    priority: "low",
    tags: ["error-handling", "programming", "best-practices"],
    author: "John Doe",
    readTime: 8,
    createdAt: new Date("2023-10-10"),
    updatedAt: new Date("2023-10-12"),
    language: "en",
  },
  {
    id: "26",
    title: "Building RESTful APIs with Express",
    status: "archived",
    priority: "low",
    tags: ["express", "api", "nodejs"],
    author: "John Doe",
    readTime: 12,
    createdAt: new Date("2023-10-05"),
    updatedAt: new Date("2023-10-07"),
    language: "en",
  },
  {
    id: "27",
    title: "Version Control with Git Advanced Techniques",
    status: "published",
    priority: "medium",
    tags: ["git", "version-control", "devops"],
    author: "John Doe",
    heroImage: "/git-advanced.png",
    readTime: 15,
    createdAt: new Date("2023-10-01"),
    updatedAt: new Date("2023-10-03"),
    language: "en",
  },
  {
    id: "28",
    title: "Security Best Practices for Web Apps",
    status: "published",
    priority: "high",
    tags: ["security", "web", "best-practices"],
    author: "John Doe",
    readTime: 16,
    createdAt: new Date("2023-09-25"),
    updatedAt: new Date("2023-09-27"),
    language: "en",
  },
  {
    id: "29",
    title: "Tailwind CSS Design System",
    status: "draft",
    priority: "low",
    tags: ["tailwind", "css", "design-system"],
    author: "John Doe",
    readTime: 9,
    createdAt: new Date("2024-01-29"),
    updatedAt: new Date("2024-01-29"),
    language: "en",
  },
  {
    id: "30",
    title: "API Rate Limiting and Throttling",
    status: "published",
    priority: "medium",
    tags: ["api", "rate-limiting", "backend"],
    author: "John Doe",
    readTime: 10,
    createdAt: new Date("2023-09-20"),
    updatedAt: new Date("2023-09-22"),
    language: "en",
  },
]

export const lcBlogs: LCBlog[] = [
  {
    id: "lc-1",
    title: "Two Sum",
    problemNumber: 1,
    difficulty: "easy",
    tags: ["array", "hash-table"],
    createdAt: new Date("2024-01-20"),
    status: "success",
    slug: "two-sum",
  },
  {
    id: "lc-2",
    title: "Add Two Numbers",
    problemNumber: 2,
    difficulty: "medium",
    tags: ["linked-list", "math"],
    createdAt: new Date("2024-01-21"),
    status: "success",
    slug: "add-two-numbers",
  },
  {
    id: "lc-3",
    title: "Longest Substring Without Repeating Characters",
    problemNumber: 3,
    difficulty: "medium",
    tags: ["string", "sliding-window"],
    createdAt: new Date("2024-01-22"),
    status: "success",
    slug: "longest-substring-without-repeating-characters",
  },
  {
    id: "lc-4",
    title: "Median of Two Sorted Arrays",
    problemNumber: 4,
    difficulty: "hard",
    tags: ["array", "binary-search"],
    createdAt: new Date("2024-01-23"),
    status: "error",
    errorMessage: "Invalid formatting: Missing problem description section",
    slug: "",
  },
  {
    id: "lc-5",
    title: "Longest Palindromic Substring",
    problemNumber: 5,
    difficulty: "medium",
    tags: ["string", "dynamic-programming"],
    createdAt: new Date("2024-01-24"),
    status: "success",
    slug: "longest-palindromic-substring",
  },
  {
    id: "lc-6",
    title: "Reverse Integer",
    problemNumber: 7,
    difficulty: "easy",
    tags: ["math"],
    createdAt: new Date("2024-01-25"),
    status: "success",
    slug: "reverse-integer",
  },
  {
    id: "lc-7",
    title: "Container With Most Water",
    problemNumber: 11,
    difficulty: "medium",
    tags: ["array", "two-pointers"],
    createdAt: new Date("2024-01-26"),
    status: "success",
    slug: "container-with-most-water",
  },
  {
    id: "lc-8",
    title: "3Sum",
    problemNumber: 15,
    difficulty: "medium",
    tags: ["array", "two-pointers"],
    createdAt: new Date("2024-01-27"),
    status: "error",
    errorMessage: "Invalid naming convention: File should be named 'lc-15-3sum.md'",
    slug: "",
  },
  {
    id: "lc-9",
    title: "Valid Parentheses",
    problemNumber: 20,
    difficulty: "easy",
    tags: ["string", "stack"],
    createdAt: new Date("2024-01-28"),
    status: "success",
    slug: "valid-parentheses",
  },
  {
    id: "lc-10",
    title: "Merge Two Sorted Lists",
    problemNumber: 21,
    difficulty: "easy",
    tags: ["linked-list", "recursion"],
    createdAt: new Date("2024-01-29"),
    status: "success",
    slug: "merge-two-sorted-lists",
  },
  {
    id: "lc-11",
    title: "Maximum Subarray",
    problemNumber: 53,
    difficulty: "medium",
    tags: ["array", "dynamic-programming"],
    createdAt: new Date("2024-01-30"),
    status: "success",
    slug: "maximum-subarray",
  },
  {
    id: "lc-12",
    title: "Climbing Stairs",
    problemNumber: 70,
    difficulty: "easy",
    tags: ["dynamic-programming", "math"],
    createdAt: new Date("2024-01-31"),
    status: "success",
    slug: "climbing-stairs",
  },
]
